GET http://localhost:3001/api/carrito

###
GET http://localhost:3001/api/carrito/61b762db1bf5e426932d3415/productos

###

POST http://localhost:3001/api/carrito
Content-Type: application/json

{
  "productos": [
    {
      "_id": "621458711c7d6ad1b803fb3d",
      "name": "Leche Gloria Light 400g",
      "price": 3.50,
      "thumbnail": ""
    }
  ]
}

###

POST http://localhost:3001/api/carrito
Content-Type: application/json

{
  "productos": [
    {
      "_id": "621458ae1c7d6ad1b803fb41",
      "name": "Aceite Soya 1L",
      "price": 5.50,
      "thumbnail": ""
    }
  ]
}

###

POST http://localhost:3001/api/carrito/62145cb700886ea3eedb64c1/comprar
Content-Type: application/json

###

PUT http://localhost:3001/api/carrito/621458db1c7d6ad1b803fb45/productos
Content-Type: application/json

{
  "_id": "61b75e7a7ab64d6edde644d8",
  "name": "Leche Gloria Light 400g",
  "price": 4,
  "thumbnail": ""
}

###

DELETE http://localhost:3001/api/carrito/621458db1c7d6ad1b803fb45